### ISSUE TITLE
Could not get API key runing pusher login

### ISSUE THREAD

**Issue by serdar** [pusher/cli#17]
Running the recently release pusher CLI windows binary I'm not able to authenticate against the server.
Steps: 
1. I've regenerated the API key in my account settings
2. Executed `pusher login`
3. Entered email address once prompted and hit enter
4. Prompted for password, then without entering anything:
5. Received the following error:

> unexpected status code 401
> The Pusher API didn't respond correctly. Please try again later!
> panic: Could not get API key: unexpected status code 401
> 
> goroutine 1 [running]:
> github.com/pusher/cli/commands/auth.glob..func1(0xb73ba0, 0xb9a790, 0x0, 0x0)
>         /Users/hugovieira/Development/Go/src/github.com/pusher/cli/commands/auth/login.go:35 +0x494
> github.com/pusher/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xb73ba0, 0xb9a790, 0x0, 0x0, 0xb73ba0, 0xb9a790)
>         /Users/hugovieira/Development/Go/src/github.com/pusher/cli/vendor/github.com/spf13/cobra/command.go:702 +0x2cd
> github.com/pusher/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc04208ad80, 0x8e76c0, 0xc04208aec0, 0xc04206ff08)
>         /Users/hugovieira/Development/Go/src/github.com/pusher/cli/vendor/github.com/spf13/cobra/command.go:783 +0x315
> github.com/pusher/cli/vendor/github.com/spf13/cobra.(*Command).Execute(0xc04208ad80, 0xc04206ff08, 0x1)
>         /Users/hugovieira/Development/Go/src/github.com/pusher/cli/vendor/github.com/spf13/cobra/command.go:736 +0x32
> main.main()
>         /Users/hugovieira/Development/Go/src/github.com/pusher/cli/main.go:30 +0x3de

**Comment by serdar** [comment]
Not familiar with Go but it appears as though you can't use 0 as a parameter to ReadPassword when on Windows. If you import "`syscall`" and change `ReadPassword` to be `ReadPassword(int(syscall.Stdin))` that should getting it running on Windows.

**Comment by hugoamvieira** [comment]
Hello @serdar, we are aware of this issue and it should be fixed in the next version.
Thank you! :)

(Also, props for finding this!)
