### ISSUE TITLE
Brew Install Fails

### ISSUE THREAD

**Issue by jackcbrown89** [pusher/cli#34]
Just a simple `brew install pusher/brew/pusher`

Gives me this error:

```
Error: Failure while executing; `unzip -qq /Users/jack/Library/Caches/Homebrew/downloads/8c29e21b50b82e85fc0d23c2650d378fdca4c2909fae8406b4390c1a211abd86--pusher_0.12_darwin_amd64.zip -d /private/tmp/d20180905-49043-187tb6y` exited with 1. Here's the output:
replace /private/tmp/d20180905-49043-187tb6y/README.md? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)
```

**Comment by Quantium** [comment]
Same issue here!

**Comment by kn100** [comment]
Hi all, 

I'd like to investigate this. Could you please let me know if you're installing Pusher CLI fresh or trying to reinstall it?

**Comment by jdempster** [comment]
From fresh here

**Comment by gabheadz** [comment]
Same issue, fresh installation.

**Comment by wilkerlucio** [comment]
Same issue here

**Comment by kn100** [comment]
Good news, this issue should now be resolved - could you try and let me know?

**Comment by kn100** [comment]
Closing as after testing the issue seens to be resolved
