### ISSUE TITLE
Cluster Config Option

### ISSUE THREAD

**Issue by miguel-fulfil** [pusher/cli#50]
Attempting to use `pusher channels apps list` (cli.pusher.com/apps.json) doesn't return apps. Our application is on cluster us3. Does cli.pusher.com have a [cluster config](https://pusher.com/docs/channels/miscellaneous/clusters/#details)?

This really becomes a problem because `pusher channels apps channel-info --app-id <<STUFF>> --channel <<STUFF>>` first calls `cli.pusher.com/apps.json`, and then returns an error: Could not get app the app: Couldn't find the app id.

**Comment by benw-pusher** [comment]
Hi, the CLI has not yet been updated to support multiple clusters at this time. I will raise this internally to see if it can be added, however note that this an alpha tool and so we can't commit to an immediate fix for this.

**Comment by marcelcorso** [comment]
Hi Miguel! 
I managed to use `channel-info` like this:

```
> pusher channels apps list
+---------+----------------+---------+
| APP ID  |    APP NAME    | CLUSTER |
+---------+----------------+---------+
| 1461353 | eu-sou-bonito  | eu      |
| 1461354 | mt-marcel-tatu | mt1     |
| 1461356 | us3-us-smart   | us3     |
+---------+----------------+---------+
```

```
> pusher channels apps channel-info --app-id 1461356 --channel some-channel
{
	"Name": "some-channel"
}
```

Maybe you used the APP NAME instead of the APP ID? (I did!) 

Can you tell us the params you used?

**Comment by benw-pusher** [comment]
We haven't had a response to this following @marcelcorso's response so I will close out. If you still need support it may be best to contact us at https://support.pusher.com/hc/en-us/requests/new
