### ISSUE TITLE
Which asset has the windows .exe

### ISSUE THREAD

**Issue by Grey-A** [pusher/cli#51]
Im trying to install the pusher cli on my windows 8 but your process isnt exactly clear for us using windows

**Comment by benw-pusher** [comment]
Hi, we are aware of an issue where the Windows version has not been correctly released and are looking into this. I'll update here when we have more info.

**Comment by benw-pusher** [comment]
Hi @Grey-A, we have now released a new version which includes the Windows release. See https://github.com/pusher/cli/releases/tag/v0.14.
